### ISSUE TITLE
main.js does not exist

### ISSUE THREAD

**Issue by scottnath** [aamirshah/generator-boom#25]
When trying to add a constant, I get the following error:

```
$ yo boom:constant blarg
[?] Enter the value for the constant 'blarg' : fargle

fs.js:432
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory '/Users/development/testing/tester/app/js/main.js'
    at Object.fs.openSync (fs.js:432:18)
    at Object.fs.readFileSync (fs.js:289:15)
    at Object.rewriteFile (/usr/local/lib/node_modules/generator-boom/util.js:9:24)
    at Generator.createViewFiles [as createConstant] (/usr/local/lib/node_modules/generator-boom/constant/index.js:56:18)
    at /usr/local/lib/node_modules/generator-boom/node_modules/yeoman-generator/lib/base.js:316:43
    at /usr/local/lib/node_modules/generator-boom/node_modules/yeoman-generator/node_modules/async/lib/async.js:551:21
    at /usr/local/lib/node_modules/generator-boom/node_modules/yeoman-generator/node_modules/async/lib/async.js:227:13
    at iterate (/usr/local/lib/node_modules/generator-boom/node_modules/yeoman-generator/node_modules/async/lib/async.js:134:13)
    at /usr/local/lib/node_modules/generator-boom/node_modules/yeoman-generator/node_modules/async/lib/async.js:145:25
    at /usr/local/lib/node_modules/generator-boom/node_modules/yeoman-generator/node_modules/async/lib/async.js:229:17
```

Looks like as per "What makes it cool" number 9. _Constants and Values will be added in main.js_, yet there is no main.js created on build.

thanks,
Scott

**Comment by aamirshah** [comment]
@scottnath We renamed `main.js` to `app.js`, looks like we forgot to change for constants. Will change it and update you. Thanks for pointing it out.

**Comment by scottnath** [comment]
Thanks @aamirshah , figured it was something like that.

**Comment by scottnath** [comment]
Works great now. Thank you!
