### ISSUE TITLE
ctor.prototype = Object.create(superCtor.prototype, {

### ISSUE THREAD

**Issue by tlimpanont** [aamirshah/generator-boom#33]
util.js:634
  ctor.prototype = Object.create(superCtor.prototype, {
                                          ^
TypeError: Cannot read property 'prototype' of undefined
    at Object.exports.inherits (util.js:634:43)
    at Object.<anonymous> (/Users/theuylimpanont/Development/generatorBoom/node_modules/browser-sync/node_modules/http-proxy/lib/http-proxy/index.js:111:17)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/theuylimpanont/Development/generatorBoom/node_modules/browser-sync/node_modules/http-proxy/lib/http-proxy.js:4:17)
    at Module._compile (module.js:460:26)

**Comment by tlimpanont** [comment]
Solution: locally npm install browser-sync seems to fixed the problem
"browser-sync": "~0.5.7",
